#!/bin/bash

bash -c "flex ritchie.l >/dev/null 2>errors.out"

if [ $? -ne 0 ]; then
  echo "Flex couldn't compile ritchie.l"
  cat errors.out
  exit 1
fi


bash -c "gcc lex.yy.c -lfl >/dev/null 2>errors.out"

if [ $? -ne 0 ]; then
  echo "GCC couldn't compile lex.yy.c"
  cat errors.out
  exit 2
fi

echo "Compiling Complete."

exit 0
