#!/bin/bash
RITCHIE_DIR=${RITCHIE_HOME:-.}
RITCHIE_FILE=${1}
${RITCHIE_DIR}/ritbuild.sh ${RITCHIE_FILE}
shift
./${RITCHIE_FILE}.out $@
rm ${RITCHIE_FILE}.out ${RITCHIE_FILE}.c ${RITCHIE_FILE}.h ${RITCHIE_FILE}.sh
