#!/bin/bash

#compiler path
compiler="../ritc"
#location of rsl.h
rsl=".."

details() {
  #compile .rit file
  bash -c "$compiler $1 &> output.out"
  
  #compile out.c
  bash -c "gcc -I$rsl out.c -lm >/dev/null 2>$1.my.out"
  
  if [ $? -ne 0 ]; then
    printf "   C code file couldn't be compiled.\n" "$1"
    printf "   See \"%s.my.out\"\n" "$1"
    printf "   and \"out.c\"\n"
    return
  fi
  
  #run a.out
  bash -c "./a.out >$1.my.out 2> /dev/null"
  
  #compare output of a.out to expected.
  paste -d@ $1.target $1.my.out | while IFS='@' read -r f1 f2 || [[ -n "$line" ]]
  do
    if [ "$f1" = "$f2" ]; then
      printf ""
    else
      printf "   Expected: %s; Received: %s\n" "$f1" "$f2"
    fi
  done
}

runtest() {
  #compile .rit file
  bash -c "$compiler $1 &>/dev/null"
  
  #compile out.c
  bash -c "gcc -I$rsl out.c -lm >/dev/null 2>$1.my.out"
  
  if [ $? -ne 0 ]; then
    printf "FAILED: %s\n" "$1"
    details $1
    return
  fi
  
  #run a.out
  bash -c "./a.out >$1.my.out 2> /dev/null"
  
  #compare output of a.out to expected.
  cmp $1.target $1.my.out > /dev/null 2> /dev/null
  if [ $? -eq 0 ]; then
    printf "pass:   %s\n" "$1"
  else
    printf "FAILED: %s\n" "$1"
    details $1
  fi
}

echo "Delete previous test results?"
echo "Press ctl-c to abort, any other key to delete prior .my.out files & run tests"
read x
rm -f *.my.out out.c out.h a.out

for filename in ./*.rit; do
  runtest $filename
done


