#!/bin/bash

rsl=".."

rm -f output.out

if [ -z "$1" ]; then
  bash -c "gcc -I$rsl out.c -lm &>output.out"
else
  bash -c "gcc -I$rsl $1.c -lm &>output.out"
fi

if [ $? -ne 0 ]; then
  printf "FAILED: C code file couldn't be compiled.\n"
else
  bash -c "./a.out"
fi


